// <auto-generated />
namespace FixesApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class servi : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(servi));
        
        string IMigrationMetadata.Id
        {
            get { return "202008181651584_servi"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
